using { CatalogService } from '../../../srv/catalog-service';

// Presentation annotations for CatalogService.Products (List Report + Object Page).
annotate CatalogService.Products with @(
  // Semantic key: FE V4 renders the draft/lock marker in this LineItem column (ADR-0015).
  Common.SemanticKey: [ name ],
  UI.HeaderInfo: {
    TypeName      : '{i18n>Products.typeName}',
    TypeNamePlural: '{i18n>Products.typeNamePlural}',
    Title         : { $Type: 'UI.DataField', Value: name },
    Description   : { $Type: 'UI.DataField', Value: category_code },
    ImageUrl      : imageUrl
  },
  UI.SelectionFields: [ name, category_code, price ],
  UI.LineItem: [
    { $Type: 'UI.DataField', Value: name },
    { $Type: 'UI.DataField', Value: category_code },
    { $Type: 'UI.DataField', Value: subcategory_code },
    { $Type: 'UI.DataField', Value: price },
    { $Type: 'UI.DataField', Value: stock },
    // Label is explicit: FE takes a DataFieldForAnnotation header from the record, not from @title.
    { $Type: 'UI.DataFieldForAnnotation', Label: '{i18n>Products.rating}', Target: '@UI.DataPoint#Rating', ![@UI.Importance]: #Low },
    // Excel import (ADR-0021): collection-bound action in the table toolbar, hidden for non-editors (ADR-0013).
    {
      $Type         : 'UI.DataFieldForAction',
      Action        : 'CatalogService.importProducts',
      Label         : '{i18n>Products.action.import}',
      ![@UI.Hidden] : { $edmJson: { $Not: { $Path: '/Permissions/isEditor' } } }
    }
  ],
  // Read-only stars in the table, interactive stars in the Object Page edit mode; no Title/Description.
  UI.DataPoint #Rating: {
    Value        : rating,
    TargetValue  : 5,
    Visualization: #Rating
  },
  UI.Facets: [
    { $Type: 'UI.ReferenceFacet', ID: 'GeneralInfo',  Label: '{i18n>Products.facet.general}', Target: '@UI.FieldGroup#GeneralInfo' },
    { $Type: 'UI.ReferenceFacet', ID: 'PricingStock', Label: '{i18n>Products.facet.pricing}', Target: '@UI.FieldGroup#PricingStock' },
    { $Type: 'UI.ReferenceFacet', ID: 'AdminData',    Label: '{i18n>Products.facet.admin}',   Target: '@UI.FieldGroup#AdminData' }
  ],
  UI.FieldGroup #GeneralInfo: { Data: [
    { $Type: 'UI.DataField', Value: name },
    { $Type: 'UI.DataField', Value: description },
    { $Type: 'UI.DataField', Value: category_code },
    { $Type: 'UI.DataField', Value: subcategory_code },
    { $Type: 'UI.DataFieldForAnnotation', Label: '{i18n>Products.rating}', Target: '@UI.DataPoint#Rating' },
    { $Type: 'UI.DataField', Value: imageUrl }
  ]},
  UI.FieldGroup #PricingStock: { Data: [
    { $Type: 'UI.DataField', Value: price },
    { $Type: 'UI.DataField', Value: currency_code },
    { $Type: 'UI.DataField', Value: stock }
  ]},
  UI.FieldGroup #AdminData: { Data: [
    { $Type: 'UI.DataField', Value: createdAt },
    { $Type: 'UI.DataField', Value: createdBy },
    { $Type: 'UI.DataField', Value: modifiedAt },
    { $Type: 'UI.DataField', Value: modifiedBy }
  ]}
);

annotate CatalogService.Products with {
  // Category is a fixed code list: dropdown with localized names, never the code.
  // Common.ValueList is generated by the compiler from sap.common.CodeList (ADR-0011).
  category @(
    Common.Text                     : category.name,
    Common.TextArrangement          : #TextOnly,
    Common.ValueListWithFixedValues : true
  );
  // Subcategory depends on the category (ADR-0024 decision 1): the one ValueList is written by hand to add the
  // In parameter category_code, it replaces the compiler-generated one; dropdown and name-only text as for category.
  subcategory @(
    Common.Text                     : subcategory.name,
    Common.TextArrangement          : #TextOnly,
    Common.ValueListWithFixedValues : true,
    Common.ValueList                : {
      Label          : '{i18n>Products.subcategory}',
      CollectionPath : 'Subcategories',
      Parameters     : [
        { $Type: 'Common.ValueListParameterInOut', LocalDataProperty: subcategory_code, ValueListProperty: 'code' },
        { $Type: 'Common.ValueListParameterIn', LocalDataProperty: category_code, ValueListProperty: 'category_code' },
        { $Type: 'Common.ValueListParameterDisplayOnly', ValueListProperty: 'name' }
      ]
    }
  );
};

// Category change on a draft (ADR-0024 decision 3): the server empties a subcategory of the old category in
// before('PATCH', Products.drafts); this side effect makes Fiori Elements re-read the field and its text.
annotate CatalogService.Products with @(
  Common.SideEffects #CategoryChanged: {
    SourceProperties: [ category_code ],
    TargetProperties: [ 'subcategory_code', 'subcategory/name' ]
  }
);

// Role-aware standard actions (ADR-0013 part 8): hidden for anyone who is not a CatalogEditor.
// The flag comes from the CatalogService.Permissions singleton, filled in srv/catalog-service.js, and is
// read through the documented short path /Permissions/isEditor (capire "Role-based Visibility").
annotate CatalogService.Products with @(
  UI.CreateHidden: { $edmJson: { $Not: { $Path: '/Permissions/isEditor' } } },
  UI.UpdateHidden: { $edmJson: { $Not: { $Path: '/Permissions/isEditor' } } },
  UI.DeleteHidden: { $edmJson: { $Not: { $Path: '/Permissions/isEditor' } } }
);

// Refresh after the Excel import (ADR-0021 amendment A): the action returns a count, so Fiori Elements
// reloads the Products list only through this side effect on the whole entity set.
annotate CatalogService.Products with actions {
  importProducts @Common.SideEffects: { TargetEntities: ['/CatalogService.EntityContainer/Products'] };
};
