using { CatalogService } from '../../../srv/catalog-service';

// Presentation annotations for CatalogService.Products (List Report + Object Page).
annotate CatalogService.Products with @(
  // Semantic key: FE V4 renders the draft/lock marker in this LineItem column (ADR-0015).
  Common.SemanticKey: [ name ],
  UI.HeaderInfo: {
    TypeName      : '{i18n>Products.typeName}',
    TypeNamePlural: '{i18n>Products.typeNamePlural}',
    Title         : { $Type: 'UI.DataField', Value: name },
    Description   : { $Type: 'UI.DataField', Value: category_code },
    ImageUrl      : imageUrl
  },
  UI.SelectionFields: [ name, category_code, price ],
  UI.LineItem: [
    { $Type: 'UI.DataField', Value: name },
    { $Type: 'UI.DataField', Value: category_code },
    { $Type: 'UI.DataField', Value: price },
    { $Type: 'UI.DataField', Value: stock }
  ],
  UI.Facets: [
    { $Type: 'UI.ReferenceFacet', ID: 'GeneralInfo',  Label: '{i18n>Products.facet.general}', Target: '@UI.FieldGroup#GeneralInfo' },
    { $Type: 'UI.ReferenceFacet', ID: 'PricingStock', Label: '{i18n>Products.facet.pricing}', Target: '@UI.FieldGroup#PricingStock' },
    { $Type: 'UI.ReferenceFacet', ID: 'AdminData',    Label: '{i18n>Products.facet.admin}',   Target: '@UI.FieldGroup#AdminData' }
  ],
  UI.FieldGroup #GeneralInfo: { Data: [
    { $Type: 'UI.DataField', Value: name },
    { $Type: 'UI.DataField', Value: description },
    { $Type: 'UI.DataField', Value: category_code },
    { $Type: 'UI.DataField', Value: imageUrl }
  ]},
  UI.FieldGroup #PricingStock: { Data: [
    { $Type: 'UI.DataField', Value: price },
    { $Type: 'UI.DataField', Value: currency_code },
    { $Type: 'UI.DataField', Value: stock }
  ]},
  UI.FieldGroup #AdminData: { Data: [
    { $Type: 'UI.DataField', Value: createdAt },
    { $Type: 'UI.DataField', Value: createdBy },
    { $Type: 'UI.DataField', Value: modifiedAt },
    { $Type: 'UI.DataField', Value: modifiedBy }
  ]}
);

annotate CatalogService.Products with {
  // Category is a fixed code list: dropdown with localized names, never the code.
  // Common.ValueList is generated by the compiler from sap.common.CodeList (ADR-0011).
  category @(
    Common.Text                     : category.name,
    Common.TextArrangement          : #TextOnly,
    Common.ValueListWithFixedValues : true
  );
};
