/**
 * The single list of pipeline-protected paths, shared by the PreToolUse hooks
 * (Edit/Write and Bash) and by the git-based gates (SubagentStop, Stop). ADR-0016.
 */
import { isUnder } from './hook-utils.mjs';

export const PROTECTED = [
  'mta.yaml',
  'xs-security.json',
  'app/**/ui5-deploy.yaml',
  '**/package-lock.json',
  'package-lock.json',
  '.claude/**',
  '.mcp.json',
  'scripts/hooks/**',
  'scripts/lib/**',
  'docs/registry/**',
  'docs/ai-pipeline-plan.md',
  'app/**/webapp/manifest.json',
];

export const PROTECTED_EXCEPTIONS = ['.claude/agent-memory/**'];

export const REASONS = {
  'docs/registry/**':
    'generated by a script; run `npm run docs:registry` instead of editing by hand',
  'scripts/hooks/**': 'hook scripts are changed only by a human; ask the user',
  'scripts/lib/**': 'hook libraries are changed only by a human; ask the user',
  '.claude/**': 'agent configuration is protected; ask the user to make the change',
  '.mcp.json':
    'MCP configuration is protected; versions are bumped through upstream-check by the user decision',
  'docs/ai-pipeline-plan.md': 'the plan is edited only on a direct request from the user',
  'app/**/webapp/manifest.json':
    'manifest.json is changed only through Fiori MCP (`mcp__fiori-mcp__list_functionality` \u2192 `get_functionality_details` \u2192 `execute_functionality`), CLAUDE.md invariant 1 and ADR-0014',
};

/** Returns the matching protected glob for a repo-relative path, or null. */
export function protectedHit(r) {
  if (isUnder(r, PROTECTED_EXCEPTIONS)) return null;
  return PROTECTED.find((g) => isUnder(r, g)) || null;
}

export function reasonFor(hit) {
  return REASONS[hit] || 'the file is protected; changing it requires an explicit user request';
}
