/**
 * The single list of pipeline-protected paths, shared by the PreToolUse hooks
 * (Edit/Write and Bash) and by the git-based gates (SubagentStop, Stop). ADR-0016.
 * Generated files are sanctioned by their content, not by the tool that wrote them (ADR-0017):
 * the guards still deny a direct edit, but the gates do not audit the generator's own output.
 */
import path from 'node:path';
import { isUnder } from './hook-utils.mjs';
import { recordedHash } from './registry-sources.mjs';

export const PROTECTED = [
  'mta.yaml',
  'xs-security.json',
  'app/**/ui5-deploy.yaml',
  '**/package-lock.json',
  'package-lock.json',
  '.claude/**',
  '.mcp.json',
  'scripts/hooks/**',
  'scripts/lib/**',
  'docs/registry/**',
  'docs/ai-pipeline-plan.md',
  'app/**/webapp/manifest.json',
];

// docs/registry/.stale is a marker the PostToolUse hook writes and the generator removes; it is
// pipeline state, not protected content, and a subagent could neither read nor remove it.
export const PROTECTED_EXCEPTIONS = ['.claude/agent-memory/**', 'docs/registry/.stale'];

/**
 * Files whose only legal writer is a script. The PreToolUse guards protect them against a direct
 * edit; the git-based gates do not audit them as protected writes, because the generator leaves
 * no `edit` record by definition and its output was blocked as a hand write four times in one
 * feature run (2026-09-11). Their gate is freshness: check-docs-fresh.mjs --fix in stop-gate.mjs
 * rewrites a hand edit instead of deadlocking on the generator's output. ADR-0017.
 */
export const GENERATED = ['docs/registry/**'];
export const GENERATED_NO_HEADER = 'docs/registry/** (no generator header)';

export const REASONS = {
  'docs/registry/**':
    'generated by a script; run `npm run docs:registry` instead of editing by hand',
  [GENERATED_NO_HEADER]:
    'a docs/registry file without the generator header was written by hand; run `npm run docs:registry` to restore it',
  'scripts/hooks/**': 'hook scripts are changed only by a human; ask the user',
  'scripts/lib/**': 'hook libraries are changed only by a human; ask the user',
  '.claude/**': 'agent configuration is protected; ask the user to make the change',
  '.mcp.json':
    'MCP configuration is protected; versions are bumped through upstream-check by the user decision',
  'docs/ai-pipeline-plan.md': 'the plan is edited only on a direct request from the user',
  'app/**/webapp/manifest.json':
    'manifest.json is changed only through Fiori MCP (`mcp__fiori-mcp__list_functionality` \u2192 `get_functionality_details` \u2192 `execute_functionality`), CLAUDE.md invariant 1 and ADR-0014',
};

/** Returns the matching protected glob for a repo-relative path, or null. */
export function protectedHit(r) {
  if (isUnder(r, PROTECTED_EXCEPTIONS)) return null;
  return PROTECTED.find((g) => isUnder(r, g)) || null;
}

/**
 * The git-based gates ask this instead of protectedHit(): a generated file counts as a protected
 * write only when it lacks the generator header, i.e. it was written by hand (ADR-0017).
 */
export function protectedWriteHit(root, r) {
  if (isUnder(r, PROTECTED_EXCEPTIONS)) return null;
  if (isUnder(r, GENERATED)) {
    return recordedHash(path.resolve(root, r)) ? null : GENERATED_NO_HEADER;
  }
  return protectedHit(r);
}

export function reasonFor(hit) {
  return REASONS[hit] || 'the file is protected; changing it requires an explicit user request';
}
