// Template: UI annotations in app/<app>/annotations/<Entity>.cds. Target is always the service projection.
// Paths use dots (currency.name). Labels via i18n keys from app/<app>/webapp/i18n/; omit Label when it
// equals the element @title. Reference from app/<app>/annotations.cds with `using from './annotations/<Entity>';`.
using { cuid, managed, Currency, sap.common.CodeList } from '@sap/cds/common';

namespace my.catalog.tpl.ui;

entity Categories : CodeList { key code : String(20); }
entity Orders : cuid, managed {
  orderNo  : String(20);
  customer : String(100);
  total    : Decimal(15, 2);
  currency : Currency;
  category : Association to Categories;
}

service OrdersService {
  entity Categories as projection on ui.Categories;
  entity Orders as projection on ui.Orders
    actions { action confirm() returns Orders; };
}

annotate OrdersService.Orders with @(
  UI.HeaderInfo : {
    TypeName       : '{i18n>Orders.typeName}',
    TypeNamePlural : '{i18n>Orders.typeNamePlural}',
    Title          : { $Type: 'UI.DataField', Value: orderNo },
    Description    : { $Type: 'UI.DataField', Value: customer }
  },
  UI.SelectionFields : [ orderNo, customer, category_code ],
  UI.LineItem : [
    { $Type: 'UI.DataFieldForAction', Action: 'OrdersService.confirm', Label: '{i18n>Orders.action.confirm}' },
    { $Type: 'UI.DataField', Value: orderNo },
    { $Type: 'UI.DataField', Value: customer },
    { $Type: 'UI.DataField', Value: total },
    { $Type: 'UI.DataField', Value: category_code }
  ],
  UI.Facets : [
    { $Type: 'UI.ReferenceFacet', ID: 'General', Label: '{i18n>Orders.facet.general}', Target: '@UI.FieldGroup#General' }
  ],
  UI.FieldGroup #General : { Data: [
    { $Type: 'UI.DataField', Value: orderNo },
    { $Type: 'UI.DataField', Value: customer },
    { $Type: 'UI.DataField', Value: total },
    { $Type: 'UI.DataField', Value: category_code }
  ]}
);

// Value help on the foreign key: show the text, hide the code (ADR-0011).
// ValueList is generated by the compiler from `sap.common.CodeList` (`@cds.odata.valuelist`);
// do not write `Common.ValueList` by hand here, it would suppress the generated one (exception: the dependent block below).
annotate OrdersService.Orders with {
  category @(
    Common.Text                     : category.name,
    Common.TextArrangement          : #TextOnly,
    Common.ValueListWithFixedValues : true
  );
}

// The code list's own key needs Common.Text too, or dropdown/dialog rows show the code (ADR-0011).
annotate OrdersService.Categories with {
  code @(
    Common.Text            : name,
    Common.TextArrangement : #TextOnly
  );
}

// Dependent value help (ADR-0024 decision 1), only for a code list whose rows belong to a row of another code list:
// the one ValueList is written by hand to add the In parameter and replaces the generated one (keep it unqualified).
// Pair it with the @assert consistency check in srv/annotations and the draft reset plus SideEffects below (ADR-0024).
// annotate OrdersService.Orders with {
//   subcategory @(
//     Common.Text                     : subcategory.name,
//     Common.TextArrangement          : #TextOnly,
//     Common.ValueListWithFixedValues : true,
//     Common.ValueList                : {
//       Label          : '{i18n>Orders.subcategory}',
//       CollectionPath : 'Subcategories',
//       Parameters     : [
//         { $Type: 'Common.ValueListParameterInOut', LocalDataProperty: subcategory_code, ValueListProperty: 'code' },
//         { $Type: 'Common.ValueListParameterIn', LocalDataProperty: category_code, ValueListProperty: 'category_code' },
//         { $Type: 'Common.ValueListParameterDisplayOnly', ValueListProperty: 'name' }
//       ]
//     }
//   );
// };
// annotate OrdersService.Orders with @(
//   Common.SideEffects #CategoryChanged : {
//     SourceProperties : [ category_code ],
//     TargetProperties : [ 'subcategory_code', 'subcategory/name' ]
//   }
// );
